-- Migration 018: Make shift start_time / end_time nullable
--
-- Shifts are now date-only; times are kept in the schema for backward
-- compatibility but are no longer required.

-- Drop the time-ordering CHECK constraint by name (auto-generated by Postgres).
-- We find it dynamically so this migration is safe across fresh and existing DBs.
DO $$
DECLARE
    r RECORD;
BEGIN
    FOR r IN
        SELECT conname
        FROM pg_constraint
        WHERE conrelid = 'project_shifts'::regclass
          AND contype   = 'c'
          AND pg_get_constraintdef(oid) LIKE '%start_time < end_time%'
    LOOP
        EXECUTE 'ALTER TABLE project_shifts DROP CONSTRAINT ' || quote_ident(r.conname);
    END LOOP;
END $$;

ALTER TABLE project_shifts ALTER COLUMN start_time DROP NOT NULL;
ALTER TABLE project_shifts ALTER COLUMN end_time   DROP NOT NULL;
